# Generated by Django 4.1.3 on 2023-01-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
                ('fecha_nacimiento', models.DateTimeField(auto_now_add=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
    ]
